### ISSUE TITLE
hsla bug

### ISSUE THREAD

**Issue by yukulele** [LeaVerou/css-colors#1]
```
rgba(0,0,0,.9)
```

display :

```
hsla(NaN, Infinity%, 0%, .9)
```

http://css.coloratum.com/#rgba%280%2C0%2C0%2C.9%29

**Comment by LeaVerou** [comment]
Oh wow, it's more broken than I thought.

In any case, I'll have to rewrite how it does conversions anyway, as it gets increasingly inaccurate with semi-transparent colors.

**Comment by yukulele** [comment]
It's not (only) result to semi-transparent colors :

```
rgb(1,0,0)
```

display :

```
hsl(0, Infinity%, 0%)
```

http://css.coloratum.com/#rgb(1%2C0%2C0)

And 

```
rgb(7,0,0)
```

display :

```
hsl(0, 137%, 1%)
```

(137% !)
http://css.coloratum.com/#rgb(7%2C0%2C0)

**Comment by LeaVerou** [comment]
:(

Thanks for the update, I will keep that in mind when fixing the algorithm. I guess using <canvas> for the conversions was a bad idea after all!

**Comment by yukulele** [comment]
Maybe that can help you :
https://github.com/jquery/jquery-color
https://github.com/jquery/jquery-color/blob/2.1.0/README.md#string-methods

**Comment by LeaVerou** [comment]
Should be fixed now, not sure if Github notified you. :)
