### ISSUE TITLE
Change site url to https://leaverou.github.io/css-colors/

### ISSUE THREAD

**Issue by dotnetCarpenter** [LeaVerou/css-colors#4]
http://css.coloratum.com is expired.

**Comment by LeaVerou** [comment]
Done, thanks!

**Comment by dotnetCarpenter** [comment]
παρακαλώ

**Comment by dotnetCarpenter** [comment]
@LeaVerou Please do the same on your project page: http://lea.verou.me/projects/
I don't use CSS.coloratum often but when I do I go to your project page and end up on ~css.coloratum.com~ and then I need to search github and then I come here and have to google translate what I wrote you in greek because I don't remember... You see it's a pretty long process, just to go to a useful website.
